### ISSUE TITLE
コマンドの追加案

### ISSUE THREAD

**Issue by PTOM76** [Pitan76/item-alchemy#1]
提案者: [フリーダムわちき](https://www.youtube.com/channel/UC4Bd5e9WKr4_TejYpNPquNg)様
>ProjectEにもあったコマンド(setEMCやreloadEMC)の追加も対応なさるご予定でしょうか？

そうですね、コマンドの対応も案には入れておこうと思います。

https://youtu.be/0gVr4ccptQg

**Comment by Ecorous** [comment]
> 提案者: [フリーダムわちき](https://www.youtube.com/channel/UC4Bd5e9WKr4_TejYpNPquNg)様
> 
> > ProjectEにもあったコマンド(setEMCやreloadEMC)の追加も対応なさるご予定でしょうか？
> 
> そうですね、コマンドの対応も案には入れておこうと思います。
> 
> https://youtu.be/0gVr4ccptQg

Proposed by: Freedom Wachiki

> Do you plan to add commands (setEMC and reloadEMC) that were also in ProjectE?

Well, I think I'll include the correspondence of the command in the proposal.

https://youtu.be/0gVr4ccptQg
