### ISSUE TITLE
Instant crash loading Minecraft 1.19.2 - Latest Item Alchemy & MCPitanLibarch

### ISSUE THREAD

**Issue by Gamerbolts** [Pitan76/item-alchemy#10]
Hi again. I got the latest update for both mods and tried loading my modpack and it crashed instantly. Here is the crash log and log. Thank you :)

[crash-2022-12-13_06.27.50-client.txt](https://github.com/Pitan76/item-alchemy/files/10217861/crash-2022-12-13_06.27.50-client.txt)
[latest.log](https://github.com/Pitan76/item-alchemy/files/10217863/latest.log)

**Comment by PTOM76** [comment]
It was caused by MCPitanLibarch.
Fixed a crashing bug.
Thank you for your report.
Please wait a moment for version 1.2.7 to be approved on CurseForge.
https://www.curseforge.com/minecraft/mc-mods/mcpitanlibarch/files

**Comment by Gamerbolts** [comment]
I saw the update and did it, however 1.2.7 is for 1.19.3 and won't load on my modpack.

**Comment by PTOM76** [comment]
Please use 1.19 of 1.2.7.
I prepared two versions, 1.19.3 and 1.19 (1.19-1.19.2).

**Comment by PTOM76** [comment]
The version I specified on the CurseForge side was wrong.
https://www.curseforge.com/minecraft/mc-mods/mcpitanlibarch/files/4172007
