### ISSUE TITLE
Fabric 1.20.1 EMC Condensor "Server Closed" crash

### ISSUE THREAD

**Issue by ZoeyTheDeer** [Pitan76/item-alchemy#103]
Upon putting anything into a EMC condensor, whether shift clicking or dragging normally; The world will close with the message "Server has closed"

The modpack does have a lot of mods, though none of them have ever had a issue similar, and it persists on a superflat world as well. Logging back into the world will either instantly close, or delete the items that were inserted into the EMC collector. I've tried back tracking both Item Alchemy and it's Library a few versions and tested each, same result.

Crashlog:
[crash-2024-07-07_21.01.55-server.txt](https://github.com/user-attachments/files/16121675/crash-2024-07-07_21.01.55-server.txt)

**Comment by ZoeyTheDeer** [comment]
Update: Similar issue occurs when holding dark matter tools. Except the log states "Ticking Player" rather than entity.

**Comment by PTOM76** [comment]
thanks for your reporting
i will upload new version MCPitanLib.
