### ISSUE TITLE
philosopher's stone ; can't craft

### ISSUE THREAD

**Issue by RoyalWolfie** [Pitan76/item-alchemy#12]
Having issues crafting Alchemical Coal;

![Screenshot at 2022-12-23 03-05-41](https://user-images.githubusercontent.com/39188670/209174684-36f2c2f9-da45-47e4-947c-a2d2238df132.png)
Id assume its not implemented?

I had also tried crafting a non damaged philosopher's stone, to see if it was something to do with that.
MC Version: 1.18.2
Fabric loader: 0.14.11
Fabric Api: 0.67
Mod Version: 0.14

**Comment by PTOM76** [comment]
Not implemented yet.

**Comment by PTOM76** [comment]
For now you have to use the EMC Collector.

**Comment by PTOM76** [comment]
Added this feature.
