### ISSUE TITLE
Blocks Not Dropping Upon Being Mined

### ISSUE THREAD

**Issue by Sugar-22** [Pitan76/item-alchemy#123]
I've noticed that none of the blocks you can place from this mod will drop when mined, I've used Pickaxes, Axes, both normal minecraft and red and dark matter tools and nothing works, the block will be destroyed and doesn't drop that block, this makes moving any blocks impossible after first placing them. In my case when upgrading the different MK EMC blocks I loose whatever block I mine to put the upgraded Mk Block in it's place, which is inconvenient when I could just move the lower MK block version to a different spot or machine if the block wasn't completely destroyed. Simply put blocks are not dropping when mined they are completely destroyed.

**Comment by PTOM76** [comment]
what is version?

**Comment by PTOM76** [comment]
Released MCPitanLib v2.4.8 & CompatDatapacks v1.0.10.210
