### ISSUE TITLE
EMC values dont appear on client restart

### ISSUE THREAD

**Issue by RoyalWolfie** [Pitan76/item-alchemy#13]
On client restart, when joining a server EMC values don't appear

![2022-12-25_04 30 11](https://user-images.githubusercontent.com/39188670/209446197-926f6833-0f0b-4827-943a-5bcbdc8e80da.png)

By joining a single player world on creative then joining back, you can get the EMC values to display.

![2022-12-25_04 30 41](https://user-images.githubusercontent.com/39188670/209446212-354d50cc-d2d6-43fa-9c7b-36f6df018d1c.png)

Minecraft: 1.18.2
Item Alchemy: 0.2.0
Fabric Loader: 0.14.11
Fabric API: 0.67.0
MCPitanLibArch: 1.3.5

**Comment by PTOM76** [comment]
Thanks for your reporting!!
Fixed by making EMCManager sync on join.

**Comment by PTOM76** [comment]
It's not fixed, so I'll open it again.
You can temporarily deal with /itemalchemy reload.
