### ISSUE TITLE
Data Driven EMC Values

### ISSUE THREAD

**Issue by ryleu** [Pitan76/item-alchemy#14]
EMC values should be in a datapack so that mod (and modpack!) developers can easily add EMC values without having to touch your mod or your APIs.

If you point me in the right direction, I will extract the values to a JSON format and send it to you.

**Comment by PTOM76** [comment]
Is it impossible with config/itemalchemy/emc_config.json?
I know nothing about datapacks.

**Comment by ryleu** [comment]
It is possible to do it there, but it's much more difficult to ship a config file with another mod. I'll work on PRing data pack support.

**Comment by PTOM76** [comment]
I tried to manage EMC with "data/", how is it?

**Comment by ryleu** [comment]
that seems like exactly what i was hoping for, i'll mess with it later today once i'm on my laptop
