### ISSUE TITLE
Crush

### ISSUE THREAD

**Issue by cool-destiny** [Pitan76/item-alchemy#16]
下記環境下でワールドに入ろうとするとクラッシュします
なお入るたびに2種類ですがエラー内容が変わるので両方レポート出しておきます

When I try to enter the world under the following environment, it crashes.
I'll report both of them because the error content changes every time I try to enter the world.

Minecraft 1.19.2 Client
architectury-6.4.62-fabric
cloth-config-8.2.88-fabric
fabric-api-0.70.0+1.19.2
itemalchemy-0.2.9
mcpitanlibarch-1.3.5-1.19-fabric
RoughlyEnoughItems-9.1.580
wraith-fabricaeexnihilo-0.1.10+mc1.19.2

Crash Report
https://paste.ee/p/98D60
https://paste.ee/p/mJzbH

**Comment by PTOM76** [comment]
ご報告ありがとうございます。
Fabricae Ex NihiloとItem Alchemyの競合でしょうか、調査します。

**Comment by PTOM76** [comment]
修正しました。

**Comment by cool-destiny** [comment]
再びで申し訳ないのです
新しいバージョンでも下記環境下でワールドに入ろうとするとクラッシュします
なお入るたびに2種類ですがエラー内容が変わるので両方レポート出しておきます

Sorry to do this again.
Even with the new version, I get a crash when I try to enter the world under the following circumstances
I'm reporting both of them because the error message changes every time I try to enter the world.

Minecraft 1.19.2 Client
fabricloader 0.14.12
architectury-6.4.62-fabric
cloth-config-8.2.88-fabric
fabric-api-0.70.0+1.19.2
itemalchemy-0.4.0
mcpitanlibarch-1.3.5-1.19-fabric
RoughlyEnoughItems-9.1.580
wraith-fabricaeexnihilo-0.1.10+mc1.19.2

Crash Report
https://paste.ee/p/BPata
https://paste.ee/p/ii25H
