### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by cool-destiny** [Pitan76/item-alchemy#19]
Sorry to do this again.
Even with the new version, I get a crash when I try to enter the world under the following circumstances
I'm reporting both of them because the error message changes every time I try to enter the world.

再びで申し訳ないのです
新しいバージョンでも下記環境下でワールドに入ろうとするとクラッシュします
なお入るたびに2種類ですがエラー内容が変わるので両方レポート出しておきます

Minecraft 1.19.2 Client
fabricloader 0.14.12
architectury-6.4.62-fabric
cloth-config-8.2.88-fabric
fabric-api-0.70.0+1.19.2
itemalchemy-0.4.0
mcpitanlibarch-1.3.5-1.19-fabric
RoughlyEnoughItems-9.1.580
wraith-fabricaeexnihilo-0.1.10+mc1.19.2

Crash Report
https://paste.ee/p/BPata
https://paste.ee/p/ii25H

**Comment by cool-destiny** [comment]
itemalchemy-0.4.1及びitemalchemy-0.4.2でクラッシュする事なくワールドに入れました
※MOD構成は前回のにitemalchemyの最新バージョンです

対応ありがとうございました

![2023-01-03_05 06 53](https://user-images.githubusercontent.com/62122374/210275915-77c5d22f-2aca-48a5-9001-eb3625085100.png)

余談：ダークマターブロックとレッドマターブロックの解体レシピが不定形にも関わらず書式が定形レシピになってました

**Comment by PTOM76** [comment]
本当ですね。直します。

**Comment by PTOM76** [comment]
修正しました。ありがとうございます。
