### ISSUE TITLE
Game crashing when adding items to tablet

### ISSUE THREAD

**Issue by Beatrixx001** [Pitan76/item-alchemy#2]
I added the mod to a semi-large modpack and upon crafting the items from the mod everything is fine but as soon as I add a few items to the tablet(both the block and the handheld) my game gets super choppy and eventually crashes, upon reload of the world I am back at the point before I crafted any item from the mod

**Comment by PTOM76** [comment]
Is that tablet an Alchemy Table or an Alchemy Pad?
Hmm, maybe there's a big looping process somewhere.

**Comment by PTOM76** [comment]
Probably, the version of MCPitanLibarch is old, so it will be closed. If there is anything, please reopen the issue again.
