### ISSUE TITLE
[Bug]: Not getting EMC from anything

### ISSUE THREAD

**Issue by frinkifail** [Pitan76/item-alchemy#20]
so yeah, im literally not getting emc from ANYTHING, i really like EE but it's now unplayable since nothing is making emc

running macos montery
minecraft 1.18.2 singleplayer

**Comment by PTOM76** [comment]
try it.
/itemalchemy resetemc
or
/itemalchemy reloademc

**Comment by frinkifail** [comment]
ok, it works now, no idea why lmao
