### ISSUE TITLE
[Suggestion]: Make Tome of Knowledge

### ISSUE THREAD

**Issue by frinkifail** [Pitan76/item-alchemy#21]
you should really make tomb of knowledge like in the original projecte which unlocks all transmutation knowledge

**Comment by frinkifail** [comment]
you cann close this if you want

**Comment by PTOM76** [comment]
Well, it's just that the texturing and modeling will take some time. If I have time, I will try it, but if someone can provide me with a model, I will adopt it.

**Comment by frinkifail** [comment]
> can you at least add a command or other item to unlock everything? it would be super helpful

true

**Comment by OffsetMonkey538** [comment]
I'm going to try and implement this

**Comment by PTOM76** [comment]
Good.
I have an idea to use Patchouli for this implementation.

**Comment by frinkifail** [comment]
this is still not dead (real)

**Comment by OffsetMonkey538** [comment]
Yeah, I went to implement it and I think I actually did get it working, but then got distracted with find out about #64 

Related to this issue, would something like a "Tome of Stupidity" or something be a cool addition? While testing I wanted to remove all the items, but found no real way of doing that

**Comment by OffsetMonkey538** [comment]
No yeah I know how I could implement something that removes all "recipes", I was saying that there currently doesn't seem to be anything in the mod that you could use to remove all "recipes", except of course just deleting or modifying the file in the world folder.

**Comment by OffsetMonkey538** [comment]
So I thought maybe a "Tome of Stupidity" that would remove all recipes from the player would be a cool addition

**Comment by frinkifail** [comment]
> Yeah, I went to implement it and I think I actually did get it working, but then got distracted with finding out about #64
> 
> Related to this issue, would something like a "Tome of Stupidity" or something be a cool addition? While testing I wanted to remove all the items, but found no real way of doing that

WHERE IS IT I NEED ITTTTTTTTTT

**Comment by OffsetMonkey538** [comment]
I'm currently away, I'll hopefully be able to get it fully working later today when I get back

**Comment by frinkifail** [comment]
okay

**Comment by OffsetMonkey538** [comment]
You could try if the Artifacts from [here](https://github.com/Pitan76/item-alchemy/actions/runs/5694247448) work. First download the `Artifacts` archive from the link above, then extract and use the file **without** a `-something` (**not** -sources, etc) after the name.

**Comment by frinkifail** [comment]
i forgor about this lmao
still havent found another fabric mod for this purpose bc im lazy

**Comment by OffsetMonkey538** [comment]
Pretty sure the pull request is just waiting to be merged right now

**Comment by OffsetMonkey538** [comment]
Ohh interesting... I'll try to get that working then

**Comment by OffsetMonkey538** [comment]
> > Yeah, I went to implement it and I think I actually did get it working, but then got distracted with finding out about #64
> > Related to this issue, would something like a "Tome of Stupidity" or something be a cool addition? While testing I wanted to remove all the items, but found no real way of doing that
> 
> normally you just make another tome of knowledge and put it in the removal slot

Could you test the artifact from [here](https://github.com/Pitan76/item-alchemy/actions/runs/5835780617?pr=68)?

**Comment by OffsetMonkey538** [comment]
I'm pretty sure I haven't changed anything related to the `syncS2C_emc_map` method

**Comment by OffsetMonkey538** [comment]
That was changed when I merged the changes from the main branch to that dev branch. Seems to be from [this commit](https://github.com/Pitan76/item-alchemy/commit/9143f08e0120dcba71d9a43c7498b9aa03175b46)

**Comment by OffsetMonkey538** [comment]
in 1.18.2 it takes a map and two BiConsumers but in 1.20.1 it takes a map and two PacketWriters

**Comment by OffsetMonkey538** [comment]
@PTOM76 Not sure how supporting different versions of mc with different code works with how this project is set up. I'd usually create multiple branches for the multiple versions. Not sure what the best solution is with this set up.

**Comment by OffsetMonkey538** [comment]
> > I'm pretty sure I haven't changed anything related to the `syncS2C_emc_map` method
> 
> when i remove the mod it works again however

you can try in 1.18.2 for now I guess

**Comment by frinkifail** [comment]
oh jeez

**Comment by frinkifail** [comment]
this is like 8 months ago :skull:

**Comment by OffsetMonkey538** [comment]
> update, i changed to an alternate mod set and am now crashing for a different reason https://crashy.net/d67a5429-d30f-437e-8434-1a368e469736
> [crash-2023-08-11_15.50.52-server.txt](https://github.com/Pitan76/item-alchemy/files/12325056/crash-2023-08-11_15.50.52-server.txt)
> 

Same issue as before. Could you try downgrading to 1.18.2 like I said before

**Comment by frinkifail** [comment]
big happy if this works

**Comment by PTOM76** [comment]
> @PTOM76 Not sure how supporting different versions of mc with different code works with how this project is set up. I'd usually create multiple branches for the multiple versions. Not sure what the best solution is with this set up.

Hi, this problem add new API to MCPitanLib.
I already made it, so I am uploading it now.
By the way, the reason why I do not create multiple branch is because I want to make the same specification on multiple versions and I want to support multiple versions in the same file.

**Comment by OffsetMonkey538** [comment]
Could somebody test the artifact from here? https://github.com/Pitan76/item-alchemy/actions/runs/5848158668/job/15855151030?pr=68

**Comment by frinkifail** [comment]
ok in a sec

**Comment by frinkifail** [comment]
[crash.log](https://github.com/Pitan76/item-alchemy/files/12331321/crash.log)

**Comment by OffsetMonkey538** [comment]
> [crash.log](https://github.com/Pitan76/item-alchemy/files/12331321/crash.log)
> 

To me that seems like an incompatibility between [C2ME](https://modrinth.com/mod/c2me-fabric) and Architectury. Could you try without C2ME? I'm pretty sure this crash should happen with any version of this mod as it shouldn't be the problem

**Comment by frinkifail** [comment]
k lemme try

**Comment by frinkifail** [comment]
it worked!! tsym

**Comment by frinkifail** [comment]
should i close this now

**Comment by frinkifail** [comment]
the removing also works btw

**Comment by frinkifail** [comment]
<img width="437" alt="Screen Shot 2566-08-14 at 14 41 57" src="https://github.com/Pitan76/item-alchemy/assets/76682714/1ee2ea3c-3dac-422a-95df-14020e225671">

why does the item stay?

**Comment by frinkifail** [comment]
there's no errors in the console btw

**Comment by OffsetMonkey538** [comment]
it should be fine with the latest one from [here](https://github.com/Pitan76/item-alchemy/actions/runs/5852501500)

**Comment by frinkifail** [comment]
ok imma try it

**Comment by OffsetMonkey538** [comment]
> should i close this now

no need, it should automatically be closed once the pr #68 is actually merged

**Comment by frinkifail** [comment]
right ok

**Comment by frinkifail** [comment]
what is the left side on the table/pad menu for?

**Comment by OffsetMonkey538** [comment]
I honestly have no idea lol

**Comment by frinkifail** [comment]
oh well
also this issue has 50+ comments now

**Comment by OffsetMonkey538** [comment]
so does it still dupe?

**Comment by frinkifail** [comment]
not anymore

**Comment by OffsetMonkey538** [comment]
So this should be ready for merging?

**Comment by frinkifail** [comment]
so now that this works i will **_try_** to start an smp with my friend with this
also yea _i think_
