### ISSUE TITLE
EMC Condenser eats Items with no EMC value

### ISSUE THREAD

**Issue by beofhelp** [Pitan76/item-alchemy#27]
In the original mod the condensing chest doesn't consume items that don't have an EMC value. This avoids the case where expensive mod items from other mods vanish without providing any benefit. (I was in the habit of just emptying my inventory into the chest after exploring to convert the thing worth EMC and have it leave the things that weren't to store.)

**Comment by PTOM76** [comment]
Thank you for your report.
It will be fixed in the next release.
