### ISSUE TITLE
[Bug]  Alchemy Table Duping Method  in 0.4.7

### ISSUE THREAD

**Issue by MLMII** [Pitan76/item-alchemy#29]
There is a method of duping items in with the alchemy table by spam creating a stack of an item while holding that item in your hand.

For example, I "burn" a stack of dirt, giving me 64 EMC ... I then select a piece of dirt from my inventory and with the dirt selected I spam 'create' a stack of dirt and can dupe multiple stacks of dirt before the table's EMC recalculates.  I can usually dupe 3-4 stacks at a time.  

A suggestion for a fix is to use a short timer between creating items to give the EMC time to update; similar to what the mod PlayerEX uses to prevent spamming extra skill points.    https://modrinth.com/mod/playerex

Thank you for your time.

**Comment by MLMII** [comment]
After a little more testing there is something odd going on with the table creating stacks of items even when not 'spam' creating the stacks.

For example I burn a stack of dirt, giving me 64 EMC ... I then create a stack of dirt, which costs 64 EMC ... I wait a second and burn the stack of dirt, giving me 64 EMC again.    However, every few times of creating stacks of dirt using this method the table will give me a stack of dirt but subtract less than 64 EMC, this number seems to be semi random, but usually it subtracts somewhere between 15-45 EMC.   This leads to EMC duping.


I haven't noticed the issue in creating single items at a time.

**Comment by PTOM76** [comment]
I tried to fix it, but I couldn't find the cause.

**Comment by PTOM76** [comment]
It's a terrible bug, so for now, I'm going to disable bulk retrieval.
I couldn't fix it. Please lend me someone strength.

**Comment by PTOM76** [comment]
Fixed
