### ISSUE TITLE
WHY JUST WHY?!?!

### ISSUE THREAD

**Issue by oliviathevampire** [Pitan76/item-alchemy#3]
https://github.com/Pitan76/item-alchemy/blob/556c41c916d968e6e9925500cedc3cbd8b7715b1/src/main/java/ml/pkom/itemalchemy/FabricMain.java#L14

Please use the ClientModInitializer for the love of god.

**Comment by PTOM76** [comment]
Originally I was going to make it with Architecture API, but I decided to make it compatible only with Fabric, so I forgot to fix it.

**Comment by PTOM76** [comment]
I'll leave this matter aside for a while as it may be ported to the Architecture API in the near future.
