### ISSUE TITLE
Minecraft keeps crashing with item alchemy

### ISSUE THREAD

**Issue by mallowgeist** [Pitan76/item-alchemy#32]
hello! I was trying to add in item alchemy to my mod pack, but it keeps crashing. 
I'm using fabric loader 0.14.14 launcher 0.11.1 for 1.19.2.
I uploaded the log here: https://mclo.gs/5JBKdaf

**Comment by PTOM76** [comment]
You should update your ItemAlchemy version to 0.4.9.
