### ISSUE TITLE
Unlimited EMC dupe method

### ISSUE THREAD

**Issue by Sonopitch** [Pitan76/item-alchemy#35]
Hover over the Item and press Q to drop the item by doing so you get the item without getting charged for it.
ItemAlchemy - itemalchemy-0.5.2.jar

( I play All Of Fabric 6 with this mod, I haven't tested this dupe with only this mod yet )

![Screenshot (502)](https://user-images.githubusercontent.com/127029379/222962354-bdc869f1-35f4-47db-8f5b-725437f75325.png)
![Screenshot (503)](https://user-images.githubusercontent.com/127029379/222962365-d7214aa4-208b-4d37-bb3a-13b189768b55.png)

**Comment by PTOM76** [comment]
thanks for your reporting!
