### ISSUE TITLE
新しいモジュールを追加しました

### ISSUE THREAD

**Issue by 54dsa** [Pitan76/item-alchemy#5]
あなたは私の世界百度百科事典にMCPitanLibarchモジュールを追加したいですか? 私はいくつかの詳細を必要とすることができれば、私は中国で少し速くアップロードし、VPNを必要としないかもしれません

**Comment by PTOM76** [comment]
What is it? Something like a mod list for Minecraft?

Item Alchemy
CurseForge: https://www.curseforge.com/minecraft/mc-mods/item-alchemy-fabric
Modrinth: https://modrinth.com/mod/item-alchemy

MCPitanLibarch
CurseForge: https://www.curseforge.com/minecraft/mc-mods/mcpitanlibarch
Modrinth: https://modrinth.com/mod/mcpitanlibarch

**Comment by 54dsa** [comment]
Like curseforge, he is a modpedia that brings together many mods and is a website in China
