### ISSUE TITLE
Crashed again!

### ISSUE THREAD

**Issue by MikeInChina** [Pitan76/item-alchemy#51]
Though your mod is good, but I have to say your mod isn't very stable. I've crashed when I tried to search in the alchemy table. It crashed when I just type the second character. I am in Minecraft1.19.2, Fabric 0.14.21, Fabric API 0.76.0, Item Alchemy 0.6.5, mcpitanlibarch 1.6.10,. Here's the report:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-06-24 21:13:42
Description: keyPressed event handler

java.lang.NoSuchMethodError: 'java.lang.String net.minecraft.class_2561.method_10851()'
	at ml.pkom.itemalchemy.gui.screen.AlchemyTableScreenHandler.sortBySearch(AlchemyTableScreenHandler.java:307)
	at ml.pkom.itemalchemy.client.screen.AlchemyTableScreen.method_16803(AlchemyTableScreen.java:59)
	at net.minecraft.class_309.method_1454(class_309.java:376)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ml.pkom.itemalchemy.gui.screen.AlchemyTableScreenHandler.sortBySearch(AlchemyTableScreenHandler.java:307)
	at ml.pkom.itemalchemy.client.screen.AlchemyTableScreen.method_16803(AlchemyTableScreen.java:59)
	at net.minecraft.class_309.method_1454(class_309.java:376)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected screen --
Details:
	Screen name: ml.pkom.itemalchemy.client.screen.AlchemyTableScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_309.method_1466(class_309.java:370)
	at net.minecraft.class_309.method_22678(class_309.java:462)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_309.method_22676(class_309.java:462)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['rimu_awa'/216, l='ClientLevel', x=-265.04, y=71.00, z=-346.08]]
	Chunk stats: 4096, 1261
	Level dimension: minecraft:overworld
	Level spawn location: World: (-263,71,-346), Section: (at 9,7,6 in -17,4,-22; chunk contains blocks -272,-64,-352 to -257,319,-337), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 131317 game time, 64341 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, 3D.Default.1.19.3.v1.8.0.zip, continuity/default, Minecraft-Mod-Language-Modpack-1-18-FabricT1-19-1o2-Fabric.zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 19.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3330459280 bytes (3176 MiB) / 7281311744 bytes (6944 MiB) up to 7281311744 bytes (6944 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12500H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x25a0
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Graphics card #1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x46a6
	Graphics card #1 versionInfo: DriverVersion=31.0.101.4032
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25950.70
	Virtual memory used (MB): 18877.06
	Swap memory total (MB): 9862.21
	Swap memory used (MB): 36.33
	JVM Flags: 11 total; -Xmx6940m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		adorn: Adorn 3.9.1+1.19.2
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.5.69
		armorchroma: Armor Chroma 1.2.3
		bclib: BCLib 2.1.7
		bettercombat: Better Combat 1.7.1+1.19
		betterend: Better End 2.1.6
		betternether: Better Nether 7.1.4
		betterstats: Better Statistics Screen 2.9.3+1.19.2
			tcdcommons: TCD Commons API 2.9.1+1.19.2
		bsvsb: Better Sodium Video Settings Button 3.0.2
		bugjump: BugJump 1.0.0-1.19.2
		carryon: Carry On 2.0.5.11
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.1.0
			coat: Coat 1.0.0-beta.19+mc22w17a
			completeconfig-base: completeconfig-base 2.1.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.1.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.1.0
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.1.0
		continuity: Continuity 2.0.2+1.19
		csearcher: ContainerSearcher 0.1.7+mc1.19.2
		droplight: Droplight 1.0.5
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.5+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		forgeconfigapiport: Forge Config API Port 4.2.11
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		ftblibrary: FTB Library 1902.3.12-build.170
		ftbultimine: FTB Ultimine 1902.3.5-build.65
		geckolib3: Geckolib 3.1.39
			com_eliotlash_mclib_mclib: mclib 20
		gobber2: Gobber2 2.6.61
			pugh_lib: Pugh Lib 1.4.15
			pugh_tools: Pugh Tools 1.3.23
		graveyard: The Graveyard 2.3.3
			omega-config: OmegaConfig 1.2.2-1.18.1
		handcrafted: Handcrafted 2.0.6
		homekit: HomeKit Mod 1.0.0
		i18nupdatemod: I18nUpdateMod 3.2.0
		iceberg: Iceberg 1.0.46
		identifier-translation: 标识符翻译 1_1.19-1.19.2
		indium: Indium 1.0.9+mc1.19.2
		inventoryprofilesnext: Inventory Profiles Next 1.10.4
		inventorytabs: Inventory Tabs 0.9.beta-1.19.x
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemalchemy: Item Alchemy 0.6.5
		jade: Jade 8.7.3
		java: Java HotSpot(TM) 64-Bit Server VM 19
		jecharacters: Just Enough Characters 1.19.2-4.4.0
			com_github_towdium_pinin: PinIn 1.6.0
		jei: Just Enough Items 11.6.0.1015
		jeresources: Just Enough Resources 1.2.2.200
		journeymap: Journeymap 5.9.7
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		justenoughprofessions: Just Enough Professions (JEP) 2.0.2
		lanserverproperties: Lan Server Properties 1.9
		libipn: libIPN 3.0.2
		malilib: MaLiLib 0.13.0
		mcda: MC Dungeons Armors 2.4.4
		mcdw: MC Dungeons Weapons 5.0.13-1.19
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			enchant_giver: Enchant Giver 1.3.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		mcpitanlibarch: MCPitanLib 1.6.10-1.19.2-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		minecraft: Minecraft 1.19.2
		minihud: MiniHUD 0.23.3
		modmenu: Mod Menu 4.1.2
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pfm: Paladin's Furniture 1.1.1
		player-animator: Player Animator 1.0.2
		polymorph: Polymorph 0.46.1+1.19.2
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			spectrelib: SpectreLib 0.11.0+1.19
		prism: Prism 1.0.3
		puzzleslib: Puzzles Lib 4.4.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		resourcefullib: Resourceful Lib 1.1.24
		runes: Runes 0.9.8+1.19
		smoothswapping: Smooth Swapping 0.9.2
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		spell_engine: Spell Engine 0.9.24+1.19
		spell_power: Spell Power Attribute 0.9.12+1.19
		spellbladenext: Spellblades and Such 1.0.26.1.hotfix1
		taxfreelevels: Tax Free Levels 1.3.3
		trinkets: Trinkets 3.4.2
		universalenchants: Universal Enchants 4.2.15
			extensibleenums: Extensible Enums 4.0.0
		wizards: Wizards 0.9.17+1.19
		zergatulfreecam: FreeCam 2.0.0
	Loaded Shaderpack: ComplementaryShaders_v4.6.zip
		Profile: EXTREME (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.19.2大型整合包
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/3D.Default.1.19.3.v1.8.0.zip (incompatible), continuity/default, file/Minecraft-Mod-Language-Modpack-1-18-FabricT1-19-1o2-Fabric.zip
	Current Language: 简体中文 (中国大陆)
	CPU: 16x 12th Gen Intel(R) Core(TM) i5-12500H
	Server Running: false
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
Thanks for your helping!

**Comment by RetroRider5** [comment]
Bro same.
