### ISSUE TITLE
提案

### ISSUE THREAD

**Issue by 54dsa** [Pitan76/item-alchemy#6]
ポータブル変換テーブルの価格は低すぎるし、作るのは簡単すぎる、暗黒物質のもの、EMC値のない多くの項目、うまくいけば、著者が燃料を補給し、私は中国語の中国語化を助けることができます
     ここに私の漢化があります
[zh_cn.zip](https://github.com/Pitan76/item-alchemy/files/10094316/zh_cn.zip)

**Comment by PTOM76** [comment]
I think that the EMC value is almost the same as Project E.
This value can be changed in emc_config.json.
我认为EMC值和Project E差不多。
可以在 emc_config.json 中更改此值。

**Comment by PTOM76** [comment]
Added Chinese.
Thank you.
