### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Rogenar** [Pitan76/item-alchemy#67]
![256539370-b3cdfa81-2158-41de-92aa-9509f5275b8f](https://github.com/Pitan76/item-alchemy/assets/122460325/a59d4410-eae3-41ce-9cf9-3f465fa20cd5)
[latest.log](https://github.com/Pitan76/item-alchemy/files/12186059/latest.log)
at ml.pkom.itemalchemy.ItemAlchemyClient.lambda$init$2(ItemAlchemyClient.java:44) ~[itemalchemy-0.7.1.jar:?]
at ml.pkom.mcpitanlibarch.api.network.ClientNetworking.lambda$registerReceiver$0(ClientNetworking.java:17) ~[mcpitanlibarch-1.7.5-1.20.1-fabric.jar:?]

**Comment by PTOM76** [comment]
how many items have you registered?
a rough number is ok

**Comment by Rogenar** [comment]
![ss4](https://github.com/Pitan76/item-alchemy/assets/122460325/9004bd6a-0933-4837-b9e1-47911ed4868f)

**Comment by PTOM76** [comment]
i probably fixed it.
if it have any bugs please open again.

**Comment by Rogenar** [comment]
item alcemy mod conflicts with botany pots tiers. that was the only problem. I reported it to the producer of the botany pots tiers mod, he said the problem was in the item alcemy mod.
