### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by Dill9** [Pitan76/item-alchemy#72]
Most items durability are at 16
![sdfhsasf](https://github.com/Pitan76/item-alchemy/assets/136808022/e9d24c02-9fa1-44d2-8ac5-6f83f29af391)
![image](https://github.com/Pitan76/item-alchemy/assets/136808022/d5b67528-df35-43c6-ba65-e0dc4fdcacad)
![image](https://github.com/Pitan76/item-alchemy/assets/136808022/fd6b0696-95d3-4def-b22f-0981d626e9a7)

**Comment by mymai1208** [comment]
Hello.
It seems that the Durability was not infinite due to a bug.
The bug has been fixed and we will release it as soon as we confirm that it works.

**Comment by mymai1208** [comment]
The latest version has been released, with bugs fixed.
