### ISSUE TITLE
no crafting recipes 0.8.0 1.20.2

### ISSUE THREAD

**Issue by igniter16** [Pitan76/item-alchemy#87]
When loading into a world, there are no crafting recipes for anything in the mod
[latest.log](https://github.com/Pitan76/item-alchemy/files/13820788/latest.log)

**Comment by Blaze-Wolf** [comment]
Have the same issue with 0.7.9 1.20.4 and 0.8.0 1.20.2

**Comment by Blaze-Wolf** [comment]
Any update on when this might be fixed?

**Comment by krymzone** [comment]
Same problem, no recipes and the inventory is broken, taking things from crafting table to inventory literally deletes the item, crafting itself is very broken

**Comment by PTOM76** [comment]
Released v0.8.2
Fixed.
If you have any questions, please open it again.
Thank you for your report.
