### ISSUE TITLE
The alchemy table UI sometimes doesn't give what you click

### ISSUE THREAD

**Issue by alexdelifer** [Pitan76/item-alchemy#9]
When I use the search function to find "stone" as in "minecraft:stone", I'll see stone to the left, I'll click it and instead I'll get redstone torches.

![2022-12-12_16 57 58](https://user-images.githubusercontent.com/1463882/207163986-b4f1dfc1-7038-4142-bacd-efe56165ba87.png)

[modlist.txt](https://github.com/Pitan76/item-alchemy/files/10212320/modlist.txt)

btw love what you're doing, EE was my favourite mod back in the day, great to have something like this on fabric

**Comment by PTOM76** [comment]
Thank you for your report.
Probably fixed, but please open again if there is something.

**Comment by alexdelifer** [comment]
Awesome!
I tried building it but either my env is broken or the jar gradle task is.
I eagerly await a new version.

Thanks!

**Comment by PTOM76** [comment]
v0.1.3 has been released.
I have a Gradle build in IntelliJ IDEA.
