### ISSUE TITLE
Items/blocks created in condenser do not stack with naturally collected item

### ISSUE THREAD

**Issue by SirOllie** [Pitan76/item-alchemy#93]
This happens for everything I make in the condenser.
e.g. I have 5 diamonds that I mined. I create two new diamonds from the condenser. I now have 7 diamonds. 5 I mined and 2 I created in the condenser, I cannot combine these into a stack of 7, the newly created diamonds do not stack with the 5 natural diamonds but can stack with each other.

I thought this problem was caused by other mods, but I tested it with just Item Alchemy and the required libraries and this problem still occurs. 

Problems occurs with Item Alchemy V0.8.5

**Comment by PTOM76** [comment]
Fixed
