### ISSUE TITLE
Team Bugs

### ISSUE THREAD

**Issue by lemony-tater-tot** [Pitan76/item-alchemy#97]
So I'll get right into it:
Firstly, teams cant be left?
![image_2024-05-01_181731283](https://github.com/Pitan76/item-alchemy/assets/154468454/7caa5e56-dfc5-428d-90a0-ccfa5013521a)
You cannot kick other players
![image_2024-05-01_181831036](https://github.com/Pitan76/item-alchemy/assets/154468454/c12efe09-d797-4903-9b60-d97771f7f8aa)
and there isn't a way to transfer progress to another team.
This seems to be working for everyone else obviously. I have the dependencies. Does anyone have any idea what the issue could be?

**Comment by mymai1208** [comment]
One team is assigned per player, so even if a player has already left a team, they are still assigned to their own team.

**Comment by mymai1208** [comment]
Probably could have been fix
All that remains is to pass the pull request.
